name: pakeaja_crm
description: PakeAja CRM Mobile Application for Field Sales
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Core dependencies
  cupertino_icons: ^1.0.6
  
  # State Management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  
  # Navigation
  go_router: ^16.0.0
  
  # Database
  drift: ^2.14.1
  sqlite3_flutter_libs: ^0.5.18
  path_provider: ^2.1.1
  path: ^1.8.3
  
  # Network
  dio: ^5.4.0
  retrofit: ^4.0.3
  supabase_flutter: ^2.3.0
  connectivity_plus: ^6.1.4
  
  # Storage
  flutter_secure_storage: ^10.0.0-beta.4
  shared_preferences: ^2.2.2
  
  # UI Components
  flutter_form_builder: ^10.1.0
  form_builder_validators: ^11.2.0
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  
  # Utilities
  intl: ^0.20.2
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  freezed_annotation: ^3.1.0
  uuid: ^4.3.1
  share_plus: ^11.0.0
  
  # Device Features
  image_picker: ^1.0.7
  flutter_image_compress: ^2.1.0
  geolocator: ^14.0.2
  permission_handler: ^12.0.1
  
  # Development
  logger: ^2.0.2
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.7
  drift_dev: ^2.14.1
  retrofit_generator: ^9.7.0
  riverpod_generator: ^2.3.9
  freezed: ^3.1.0
  json_serializable: ^6.7.1
  mockito: ^5.4.4
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
  assets:
    - .env
    - assets/images/
    - assets/icons/
    - assets/fonts/
  
  # fonts:
  #   - family: Inter
  #     fonts:
  #       - asset: assets/fonts/Inter-Regular.ttf
  #       - asset: assets/fonts/Inter-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Inter-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Inter-Bold.ttf
  #         weight: 700